/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

/**
 *
 * @author Rajatha
 */
public class Dashboard extends javax.swing.JFrame {
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        lblEmail.setText(info.SessionInfo.loggedInUserEmail);
        lblName.setText(info.SessionInfo.loggedInUser);
        lblBatch.setText(info.SessionInfo.loggedInUserBatch);
        lblFaculty.setText(info.SessionInfo.loggedInUserFaculty);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEvents = new javax.swing.JButton();
        btnTimetable = new javax.swing.JButton();
        btnCMS = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();

        lblName = new javax.swing.JLabel();
        lblBatch = new javax.swing.JLabel();
        lblFaculty = new javax.swing.JLabel();

        btnLibrary = new javax.swing.JButton();

        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 181, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEvents.setText("Events");
        btnEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventsActionPerformed(evt);
            }
        });
        jPanel1.add(btnEvents, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 280, 120));

        btnTimetable.setText("Timetable");
        btnTimetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimetableActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 260, 110));

        btnCMS.setText("File a Complain");

        jPanel1.add(btnCMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 280, 120));
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 220, 60));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 190, 50));
        jPanel1.add(lblBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 80, 150, 40));
        jPanel1.add(lblFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 70, 130, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nsbmbackground.jpg"))); // NOI18N

        jPanel1.add(btnCMS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 280, 120));
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 220, 60));

        btnLibrary.setText("Library");
        btnLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibraryActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibrary, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 250, 120));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nsbmappbackground.jpg"))); // NOI18N

        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventsActionPerformed
        events.Events eventsForm = new events.Events(this);
        eventsForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEventsActionPerformed


    private void btnTimetableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimetableActionPerformed
        timetables.Student_Time_Table timetableForm = new timetables.Student_Time_Table();
        timetableForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTimetableActionPerformed

    private void btnLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibraryActionPerformed
       library.LibraryDashboard libraryDash = new library.LibraryDashboard();
       libraryDash.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnLibraryActionPerformed


    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCMS;
    private javax.swing.JButton btnEvents;
    private javax.swing.JButton btnLibrary;
    private javax.swing.JButton btnTimetable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFaculty;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
