/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rajatha
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(58, 181, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-mail");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, -1, -1));

        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 270, 40));

        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 270, 40));

        btnLogin.setBackground(new java.awt.Color(26, 86, 158));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 370, 67));

        lblLogin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblLogin.setText("Login");
        jPanel1.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nsbmbackground.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // login button click event
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String userEmail = txtEmail.getText();
        
        if(userEmail.contains("@students.nsbm.lk")){
            loginUser("student");
        }
        else if(userEmail.contains("@nsbm.lk")){
            loginUser("staff");
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid credentials");
        }       
    }//GEN-LAST:event_btnLoginActionPerformed
    
    private void loginUser(String userType){
        String userEmail = txtEmail.getText();
        String userPassword = txtPassword.getText();
        
        Connection con = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;
        String query;
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(info.DBInfo.DBUrl, info.DBInfo.DBUsername, info.DBInfo.DBPassword); // database information taken from DBInfo class

            if(userType.equals("student")){
                query = "select * from student where st_email=? and st_pwd=?";
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, userEmail);
                pstmt.setString(2, userPassword);
                rs = pstmt.executeQuery();
                // if login credentials are valid redirect to home page
                if(rs.next()){
                    String name = rs.getString(3);
                    String batch = rs.getString(5);
                    String faculty = rs.getString(6);
                    info.SessionInfo.loggedInUserEmail = userEmail;
                    info.SessionInfo.loggedInUser = name;
                    info.SessionInfo.loggedInUserBatch = batch;
                    info.SessionInfo.loggedInUserFaculty = faculty;
                    Dashboard dashboardForm = new Dashboard();
                    dashboardForm.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid credentials"); //  if login credentials are invalid, show error
                }
            }
            else if(userType.equals("staff")){
                query = "select * from staff where emp_email=? and emp_pwd=?";
                pstmt = con.prepareStatement(query);
                pstmt.setString(1, userEmail);
                pstmt.setString(2, userPassword);
                rs = pstmt.executeQuery();
                // if user credentials found in staff table redirect to admin dashboard
                if(rs.next()){
                    info.SessionInfo.loggedInUserEmail = userEmail;
                    admin.AdminDashboard adminDashboardForm = new admin.AdminDashboard();
                    adminDashboardForm.setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Invalid credentials"); //  if login credentials are invalid, show error
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Internal error, try again later.");
        }
        finally{
            if(con != null){
                try {
                    con.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
