/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Rajatha
 */
public class AddEvent extends javax.swing.JFrame {
    Image image = null;
    File file = null;
    /**
     * Creates new form AddEvent
     */
    public AddEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblVenue = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        btnAddEvent = new javax.swing.JButton();
        txtTitle = new javax.swing.JTextField();
        txtVenue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        btnAddImage = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        txtDateTime = new javax.swing.JTextField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 181, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setText("Title");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        lblVenue.setText("Venue");
        jPanel1.add(lblVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        lblDetails.setText("Details");
        jPanel1.add(lblDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        btnAddEvent.setText("Add Event");
        btnAddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 390, 110));
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 290, 40));
        jPanel1.add(txtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 290, 40));

        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        jScrollPane1.setViewportView(txtDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 290, 120));

        btnAddImage.setText("Add Image");
        btnAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImageActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 210, 60));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 220, 240));

        lblDateTime.setText("Date and Time");
        jPanel1.add(lblDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));
        jPanel1.add(txtDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 280, 40));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nsbmbackground.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        ImageIcon icon = new ImageIcon(filename);
        image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        lblImage.setIcon(icon);
    }//GEN-LAST:event_btnAddImageActionPerformed

    private void btnAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventActionPerformed
        String title = txtTitle.getText();
        String venue = txtVenue.getText();
        String dateTime = txtDateTime.getText();
        String details = txtDetails.getText();
        String eventId = title + venue;
        
        try{
            if(image != null){
                saveEvent(eventId, title, venue, dateTime, details, image);
            }
            else{
                saveEvent(eventId, title, venue, dateTime, details);
            }
            JOptionPane.showMessageDialog(null, "Event Added.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error.");
        }finally{
            EventsDashboard eventsDashboardForm = new EventsDashboard();
            eventsDashboardForm.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAddEventActionPerformed
    
    public void saveEvent(String eventId, String title, String venue, String dateTime, String details){
        Connection conn = null;
        PreparedStatement pstmt = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(info.DBInfo.DBUrl, info.DBInfo.DBUsername, info.DBInfo.DBPassword); // database information taken from DBInfo class
            String query = "insert into events(eventId, title, venue, date_time, details) values(?, ?, ?, ?, ?)";
            pstmt = conn.prepareStatement(query);
            pstmt.setString(1, eventId);
            pstmt.setString(2, title);
            pstmt.setString(3, venue);
            pstmt.setString(4, dateTime);
            pstmt.setString(5, details);
            pstmt.executeUpdate();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            if(conn != null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    // ignore exception
                }
            }
        }
    }
    
    public void saveEvent(String eventId, String title, String venue, String dateTime, String details, Image image){
        String imgName = title + venue;
        
        try{
            BufferedImage bImage = toBufferedImage(image);
            File outFile = new File("./src/events/imgs/" + imgName + ".png");
            ImageIO.write(bImage, "png", outFile);
        }catch(IOException e){
            System.out.println(e);
        }
        
        Connection conn = null;
        PreparedStatement pstmt = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(info.DBInfo.DBUrl, info.DBInfo.DBUsername, info.DBInfo.DBPassword); // database information taken from DBInfo class
            String query = "insert into events values(?, ?, ?, ?, ?, ?)";
            pstmt = conn.prepareStatement(query);
            pstmt.setString(1, eventId);
            pstmt.setString(2, title);
            pstmt.setString(3, venue);
            pstmt.setString(4, dateTime);
            pstmt.setString(5, details);
            pstmt.setString(6, imgName);
            pstmt.executeUpdate();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            if(conn != null){
                try {
                    conn.close();
                } catch (SQLException ex) {
                    // ignore exception
                }
            }
        }
    }
    
    public BufferedImage toBufferedImage(Image img) throws IOException{
        if(img instanceof BufferedImage){
            return (BufferedImage)img;
        }
        //BufferedImage bImage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
        BufferedImage bImage = ImageIO.read(file);
        Graphics2D gr = bImage.createGraphics();
        gr.drawImage(img, 0, 0, null);
        gr.dispose();
        
        return bImage;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnAddImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVenue;
    private javax.swing.JTextField txtDateTime;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
