/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Rajatha
 */
public class AddEvent extends javax.swing.JFrame {
    Image image = null;
    File file = null;
    /**
     * Creates new form AddEvent
     */
    public AddEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblVenue = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        btnAddEvent = new javax.swing.JButton();
        txtTitle = new javax.swing.JTextField();
        txtVenue = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        btnAddImage = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 181, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setText("Title");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        lblVenue.setText("Venue");
        jPanel1.add(lblVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        lblDetails.setText("Details");
        jPanel1.add(lblDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        btnAddEvent.setText("Add Event");
        btnAddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddEvent, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 390, 110));
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 290, 40));
        jPanel1.add(txtVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 290, 40));

        txtDetails.setColumns(20);
        txtDetails.setRows(5);
        jScrollPane1.setViewportView(txtDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 290, 120));

        btnAddImage.setText("Add Image");
        btnAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddImageActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 210, 60));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 220, 240));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nsbmappbackground.jpg"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddImageActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        ImageIcon icon = new ImageIcon(filename);
        image = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        lblImage.setIcon(icon);
    }//GEN-LAST:event_btnAddImageActionPerformed

    private void btnAddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventActionPerformed
        try{
            BufferedImage bImage = toBufferedImage(image);
            File outFile = new File("./src/events/imgs/logo.png");
            ImageIO.write(bImage, "png", outFile);
        }catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAddEventActionPerformed
    
    public BufferedImage toBufferedImage(Image img) throws IOException{
        if(img instanceof BufferedImage){
            return (BufferedImage)img;
        }
        //BufferedImage bImage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);
        BufferedImage bImage = ImageIO.read(file);
        Graphics2D gr = bImage.createGraphics();
        gr.drawImage(img, 0, 0, null);
        gr.dispose();
        
        return bImage;
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvent;
    private javax.swing.JButton btnAddImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVenue;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtVenue;
    // End of variables declaration//GEN-END:variables
}
